//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sektion1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int personId { get; set; }

        public int familjId { get; set; }
        public string fornamn { get; set; }
        public string efternamn { get; set; }
        public string alder { get; set; }
        public string tel { get; set; }
        public string Utbildning { get; set; }
    
        public virtual Familj Familj { get; set; }
    }
}
